/* SPDX-License-Identifier: MIT */
package io.github.follyworks.template.datagen;

import io.github.follyworks.template.TemplateMod;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.PackOutput;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.data.event.GatherDataEvent;

/**
 * STUDIO-9: every JSON this mod ships is generated by {@code ./gradlew runData} into
 * {@code src/generated/resources}, which is a source root. Nothing under {@code data/} or
 * {@code assets/} is hand-written, so a Minecraft version bump that changes a JSON shape
 * surfaces as a compile error here rather than as silent breakage at runtime.
 *
 * <p>Recipe and tag providers plug in the same way: extend {@code RecipeProvider} or
 * {@code TagsProvider}, then add one {@code gen.addProvider(event.includeServer(), ...)} line.
 */
@EventBusSubscriber(modid = TemplateMod.MODID, bus = EventBusSubscriber.Bus.MOD)
public final class DataGenerators {

    private DataGenerators() {}

    @SubscribeEvent
    public static void gatherData(GatherDataEvent event) {
        DataGenerator gen = event.getGenerator();
        PackOutput output = gen.getPackOutput();

        gen.addProvider(event.includeClient(), new ModItemModelProvider(output, event.getExistingFileHelper()));
        gen.addProvider(event.includeClient(), new ModLanguageProvider(output));
    }
}
